### ISSUE TITLE
Library does not work

### ISSUE THREAD

**Issue by kennyhei** [westerveltco/django-q-registry#93]
I have Django 5.2 and Python 3.13.

I did the basic setup as instructed in the documentation and nothing happens. What I did:

1. I created new app `scheduler` with `python manage.py startapp scheduler`
2. I registered the app in `INSTALLED_APPS`
3. I created `tasks.py` file where I placed following code:

```python
from django_q.models import Schedule
from django_q_registry import register_task

print("register?")


@register_task(
    name="Send hello world",
    schedule_type=Schedule.CRON,
    # https://crontab.guru/#*/5_*_*_*_*
    cron="*/5 * * * *",
)
def test_hello_world():
    return "HELLO WORLD!"
````

I can see from `runserver` logs that print command so the code from `tasks.py` is loaded but nothing happens. I presume that this should create new Schedule object but there's nothing when I checked from admin panel. Really mysterious as running this code is not even giving me any errors or anything.

Also tested with `registry.register`, same thing, nothing happens.

**Comment by kennyhei** [comment]
Okay, it's related to me running my Django app in Docker. When I ran `python manage.py setup_periodic_tasks`, it created Schedule object successfully!

Now that I'm reading the code, have I understood the usage incorrectly? So the new tasks are saved in memory and are not registered until you run `setup_periodic_tasks`, right? I think I got confused a bit from "Setting up Periodic Tasks in Production" because I thought they would just magically register in dev environment and then in production you had to run that command 😅

**Comment by kennyhei** [comment]
I'm running my app in Docker so had some issues with django-q running old code when I made changes to my code. If this is helpful for anyone, I added this to my Dockerfile:

```
RUN pip install watchdog
```

And here's `docker-compose.yml`:

```
  qcluster:
    build: .
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- python manage.py qcluster
    restart: always
    volumes:
      - ".:/app"
    env_file:
      - ".env"
    depends_on:
      - postgres
```

Now the container is restarted automatically whenever changes are made to Python files. Could be improved by targeting `tasks.py` files only.
